version: '3.8'
services:
  db-local:
    image: postgres:14.5
    container_name: db-bench
    ports:
      - "5401:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: 
      context: ./coordinator/
    image: backend-bench:latest
    restart: always
    volumes:
      - ./src:/src
      - ./opt:/opt
    ports:
      - "80:80"
    env_file:
      - ./.env
  ressearch_backend:
    build: 
      # dockerfile: ./ressearch/Dockerfile
      context: ./ressearch/
    env_file:
      - .env
    image:
      ressearch_backend:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db-local
    
    
#    environment:
#      - API_ENVIRONMENT=local
#    healthcheck:
#      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
#      interval: 60s
#      timeout: 5s
#      retries: 5


volumes:
  pgdata: