version: '3.8'
services:
  
  db-local:
    image: postgres:14.5
    container_name: db-fastapi
    hostname: db-fastapi
    restart: always
    ports:
      - "8001:5432"
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_DB=${POSTGRES_DB_FASTAPI}
      - POSTGRES_USER=${POSTGRES_USER_FASTAPI}
      - POSTGRES_PASSWORD_FASTAPI=${POSTGRES_PASSWORD_FASTAPI}
      - POSTGRES_HOST_FASTAPI=${POSTGRES_HOST_FASTAPI}
    volumes:
      - pgdata_fastapi:/var/lib/postgresql/data
    networks:
      - backend_fastapi
  
  db-local2:
    image: postgres:14.5
    container_name: db-rails
    hostname: db-rails
    restart: always
    ports:
      - "8002:5432"
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_DB=${POSTGRES_DB_RAILS}
      - POSTGRES_USER=${POSTGRES_USER_RAILS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_RAILS}
      - POSTGRES_HOST=${POSTGRES_HOST_RAILS}
    volumes:
      - pgdata_rails:/var/lib/postgresql/data
    networks:
      - backend_rails

  # FastAPI application
  coordinator_backend:
    build: 
      context: ./coordinator/
      network: host
    image: backend-bench:latest
    hostname: coordinator
    container_name: bench-backend-fastapi
    restart: always
    volumes:
      - ./coordinator/:/app/
    ports:
      - "80:80"
    env_file:
      - ./.env
    networks:
      - backend_fastapi
      - backend_communicator
      - kafka-net
    depends_on:
      - db-local
      - ressearch_backend
      - finance_backend
      - rabbitmq
      - kafka
  
  # Django application
  support_backend:
    build:
      context: ./support/
      network: host
    hostname: support
    image: backend-bench-django:latest
    container_name: bench-backend-django
    env_file:
      - ./.env
    ports:
      - "3003:3003"
    networks:
      - backend_communicator
    depends_on:
      - coordinator_backend
    volumes:
      - ./support/:/app/
  
  # Rails application
  # ressearch_backend:
  #   build:
  #     context: ./ressearch/
  #   container_name: bench-backend-rails
  #   hostname: ressearch
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - ./ressearch:/rails
  #   image:
  #     ressearch_backend:latest
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db-local2
  #   networks:
  #     - backend_rails
  #     - backend_communicator
  
  # Go application
  finance_backend:
    build: 
      context: ./finance/
      network: host
    container_name: bench-backend-golang
    hostname: finance
    env_file:
      - ./.env
    volumes:
      - ./finance:/app
    image: finance_backend:latest
    ports:
      - "3001:3001"
    networks:
      - backend_finance
      - backend_communicator
    
  frontend:
    build: 
      context: ./frontend
      network: host
    container_name: bench-frontend
    volumes:
      - ./frontend/app:/app
    ports:
      - "3002:3002"
    networks:
      - backend_communicator
    depends_on:
      - coordinator_backend 
  
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning # --requirepass password
    volumes: 
      - redis-cache:/data
    networks:
      - backend_communicator
  
  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: 'bench-rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - backend_communicator
    hostname: rabbitmq
    logging:
      driver: none
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    hostname: zookeeper
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=${ALLOW_ANONYMOUS_LOGIN}
    networks:
      - kafka-net
    tmpfs: "/datalog"
  
  kafka:
    image: docker.io/bitnami/kafka:2.8
    hostname: kafka
    ports:
      - "9092:9092"
      - '29092:29092'
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ALLOW_PLAINTEXT_LISTENER=${ALLOW_PLAINTEXT_LISTENER}
    depends_on:
      - zookeeper
    networks:
      - kafka-net
    
    
#    environment:
#      - API_ENVIRONMENT=local
#    healthcheck:
#      test: ["CMD", "curl", "-f", "localhost:8000/healthcheck"]
#      interval: 60s
#      timeout: 5s
#      retries: 5


volumes:
  pgdata_fastapi:
  pgdata_rails:
  redis-cache:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  rabbitmq_data:
  rabbitmq_log:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local
  metricbeatdata01:
    driver: local
  

networks:
  backend_fastapi:
    driver: bridge
  backend_rails:
    driver: bridge
  backend_finance:
    driver: bridge
  kafka-net:
    driver: bridge
  backend_communicator: