import os

JWT_TOKEN_EXPIRE_MINUTES: int = 30

PG_HOST = os.getenv('POSTGRES_HOST_FASTAPI')
PG_PORT = os.getenv('POSTGRES_PORT')
PG_PASSWORD = os.getenv('POSTGRES_PASSWORD_FASTAPI')
PG_USER = os.getenv('POSTGRES_USER_FASTAPI')
PG_DB = os.getenv('POSTGRES_DB_FASTAPI')

JWT_SECRET = os.getenv('JWT_SECRET')